//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Photogf.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class fileManager
    {
        public int id { get; set; }
        public string fileName { get; set; }
        public string filePath { get; set; }
        public string fileTitle { get; set; }
        public string fileContent { get; set; }
        public System.DateTime addTime { get; set; }
        public string fileType { get; set; }
        public int productID { get; set; }
    }
}
