//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Photogf.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Manager
    {
        public int id { get; set; }
        public string userName { get; set; }
        public string password { get; set; }
        public string NickName { get; set; }
        public string img { get; set; }
        public System.DateTime addTime { get; set; }
        public bool power { get; set; }
    }
}
